version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=password
      - TS_TUNE_MAX_CONNS=1000
      - POSTGRES_DB=bank_tests
    ports:
      - "54322:5432"
    healthcheck:
      test: "pg_isready -U postgres"
      start_period: 10s
      interval: 2s
      timeout: 2s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - GO_ENV=production
      - GIN_MODE=release
      - DB_SOURCE=postgres://postgres:password@timescaledb:5432/bank_tests?sslmode=disable
    depends_on:
      timescaledb:
        condition: service_healthy
    ports:
      - "8080:8080"
