---
development:
  dialect: postgres
  database: bank_tests
  user: postgres
  password: password
  host: 127.0.0.1
  port: 54322
  pool: 5

production:
  url: {{envOr "DB_PRODUCTION" "postgres://postgres:password@localhost:5432/bank_tests?sslmode=disable"}}
